---
- name: Ensure cnc_agent component directory exists
  ansible.builtin.file:
    path: "{{ agent.vender_dir }}/cnc_agent"
    state: directory
    mode: "0755"

- name: Vendor cnc_agent.py
  ansible.builtin.copy:
    src: "{{ agent.source_dir }}/cnc_agent.py"
    dest: "{{ agent.vender_dir }}/cnc_agent/cnc_agent.py"
    mode: "0644"
    remote_src: true

- name: Vendor cnc_agent __init__.py
  ansible.builtin.copy:
    dest: "{{ agent.vender_dir }}/cnc_agent/__init__.py"
    content: |
      from .cnc_agent import load_component
      __all__ = ['load_component']
    mode: "0644"

- name: Ensure cnc_metadata component directory exists
  ansible.builtin.file:
    path: "{{ agent.vender_dir }}/cnc_metadata"
    state: directory
    mode: "0755"

- name: Vendor cnc_metadata.py
  ansible.builtin.copy:
    src: "{{ agent.source_dir }}/cnc_metadata.py"
    dest: "{{ agent.vender_dir }}/cnc_metadata/cnc_metadata.py"
    mode: "0644"
    remote_src: true

- name: Vendor cnc_metadata __init__.py
  ansible.builtin.copy:
    dest: "{{ agent.vender_dir }}/cnc_metadata/__init__.py"
    content: |
      from .cnc_metadata import load_component
      __all__ = ['load_component']
    mode: "0644"
