---
repo:
  url: https://github.com/E3CNC/E3CNC_UI.git
  dest: '{{ ansible_env.HOME }}/E3CNC_UI'
  branch: main

frontend:
  web_root: '{{ ansible_env.HOME }}/mainsail'

agent:
  vender_dir: '{{ ansible_env.HOME }}/moonraker/moonraker/components'
  source_dir: '{{ repo.dest }}/E3CNC/moonraker-mcp'

klipper:
  extras_dir: '{{ ansible_env.HOME }}/klipper/klippy/extras'

printer_data:
  config_dir: '{{ ansible_env.HOME }}/printer_data/config'
  E3CNC_dir: '{{ ansible_env.HOME }}/printer_data/config/E3CNC'
  scripts_dir: '{{ ansible_env.HOME }}/printer_data/scripts'
  macros_dir: '{{ ansible_env.HOME }}/printer_data/config/macros'
  printer_cfg: '{{ ansible_env.HOME }}/printer_data/config/printer.cfg'

moonraker_conf: '{{ ansible_env.HOME }}/printer_data/config/moonraker.conf'
