---
- name: Ensure [cnc_agent] section header in moonraker.conf
  ansible.builtin.lineinfile:
    path: '{{ moonraker_conf }}'
    line: '[cnc_agent]'
    insertbefore: EOF
    create: true

- name: Ensure [cnc_metadata] section header in moonraker.conf
  ansible.builtin.lineinfile:
    path: '{{ moonraker_conf }}'
    line: '[cnc_metadata]'
    insertbefore: EOF
    create: true

- name: Ensure extractor_path in [cnc_metadata] section
  ansible.builtin.lineinfile:
    path: '{{ moonraker_conf }}'
    regexp: '^extractor_path:'
    line: 'extractor_path: {{ printer_data.scripts_dir }}/cnc_metadata_extractor.py'
    insertafter: '\[cnc_metadata\]'

- name: Ensure timeout in [cnc_metadata] section
  ansible.builtin.lineinfile:
    path: '{{ moonraker_conf }}'
    regexp: '^timeout:'
    line: 'timeout: 30.0'
    insertafter: '\[cnc_metadata\]'
